### ISSUE TITLE
server connection issue

### ISSUE THREAD

**Issue by muhammedfurkan** [saltudelft/type4py-vscode-ext#22] opened 2021-12-09 12:50 UTC
![image](https://user-images.githubusercontent.com/9547040/145399582-fbca022a-47d8-40c6-b70d-5bd528507dff.png)

**Comment by mir-am** [comment] 2021-12-09 15:29
Thank you for using Type4Py and posting the issue.
That error is often related to the internet connection issue. Please make sure that you are connected to the internet when using the extension.
I have checked out and our server is up.

**Comment by muhammedfurkan** [comment] 2021-12-12 16:25
> Thank you for using Type4Py and posting the issue. That error is often related to the internet connection issue. Please make sure that you are connected to the internet when using the extension. I have checked out and our server is up.

I cant connect, still.

**Comment by mir-am** [comment] 2021-12-13 13:52
> > Thank you for using Type4Py and posting the issue. That error is often related to the internet connection issue. Please make sure that you are connected to the internet when using the extension. I have checked out and our server is up.
> 
> I cant connect, still.

Could you please update VSCode and the extension to the latest version and report if the issue persists?
Unfortunately, I couldn't reproduce the issue on my own system.

**Comment by CoderUndefined** [comment] 2022-01-02 22:06
Same issue as described above. No connection, even on two different computers.
VSCode was very recently downloaded, version 1.63.2.
Using latest version of the type4py vscode extension.

I am aware that there were holidays, so it might be that.

**Comment by mir-am** [comment] 2022-01-02 23:16
> Same issue as described above. No connection, even on two different computers. VSCode was very recently downloaded, version 1.63.2. Using latest version of the type4py vscode extension.
> 
> Any additional specific configuration is required?
> 
> I am aware that there were holidays, so it might be that.

Thanks for reporting an issue.
I have tested the extension v.`0.1.6` on my machine with VSCode `1.63.2`. It works as expected.
There are no specific configurations. Users should follow the usage guide in `README`.
Could you tell us what is your OS? or do you happen to have a firewall or antivirus (they might block the connection to the server)?

**Comment by CoderUndefined** [comment] 2022-01-03 08:51
After digging in the logs, I found this, which happens exactly when I try.
It implies that the TLS/SSL certificate has expired.

[2022-01-03 09:43:46.584] [renderer1] [error] [Extension Host] Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

Note that this is just for trying out. In the long run I am more interested in the JSON response and due to the potential large number of requests, I would rather run a Type4Py server locally if possible to avoid straining your server

**Comment by mir-am** [comment] 2022-02-20 21:19
@CoderUndefined
Check out [this wiki page](https://github.com/saltudelft/type4py/wiki/Using-Type4Py-Rest-API) on how to use Type4Py's public API.
I am going to close this issue.

**Closed by mir-am** 2022-02-20 21:19 UTC
